spring.application.name=grocery-backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/grocery_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:your_mysql_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always

jwt.secret=${JWT_SECRET:OPUpr1tz+GfQzvXMw6aaQjs136qnxOpWDZNUIKSzEefilqgP6Nu+bR0oemqNNvRilC1MFLyc+FFhMW/9Mq8JtA==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
